dtmc

 module jpfModel
state : [0 ..61] init 0;
bsearcherfound: bool init false;
[] state = 0 -> 1.0:(state'=1) & (bsearcherfound'= false);
[] state = 1 -> 0.5:(state'=2) & (bsearcherfound'= false) + 0.3:(state'=53) & (bsearcherfound'= false) + 0.2:(state'=55) & (bsearcherfound'= false);
[] state = 2 -> 1.0:(state'=3) & (bsearcherfound'= false);
[] state = 3 -> 0.3:(state'=49) & (bsearcherfound'= false) + 0.2:(state'=51) & (bsearcherfound'= false) + 0.5:(state'=4) & (bsearcherfound'= false);
[] state = 4 -> 1.0:(state'=5) & (bsearcherfound'= false);
[] state = 5 -> 0.5:(state'=6) & (bsearcherfound'= false) + 0.3:(state'=45) & (bsearcherfound'= false) + 0.2:(state'=47) & (bsearcherfound'= false);
[] state = 6 -> 1.0:(state'=7) & (bsearcherfound'= false);
[] state = 7 -> 0.5:(state'=8) & (bsearcherfound'= false) + 0.3:(state'=41) & (bsearcherfound'= false) + 0.2:(state'=43) & (bsearcherfound'= false);
[] state = 8 -> 1.0:(state'=9) & (bsearcherfound'= false);
[] state = 9 -> 0.2:(state'=39) & (bsearcherfound'= false) + 0.5:(state'=10) & (bsearcherfound'= false) + 0.3:(state'=13) & (bsearcherfound'= false);
[] state = 10 -> 1.0:(state'=11) & (bsearcherfound'= true);
[] state = 11 -> 1.0:(state'=61) & (bsearcherfound'= true);
[] state = 13 -> 1.0:(state'=14) & (bsearcherfound'= false);
[] state = 14 -> 0.3:(state'=35) & (bsearcherfound'= false) + 0.2:(state'=37) & (bsearcherfound'= false) + 0.5:(state'=15) & (bsearcherfound'= false);
[] state = 15 -> 1.0:(state'=16) & (bsearcherfound'= false);
[] state = 16 -> 0.5:(state'=17) & (bsearcherfound'= false) + 0.2:(state'=33) & (bsearcherfound'= false) + 0.3:(state'=31) & (bsearcherfound'= false);
[] state = 17 -> 1.0:(state'=18) & (bsearcherfound'= false);
[] state = 18 -> 0.5:(state'=19) & (bsearcherfound'= false) + 0.3:(state'=27) & (bsearcherfound'= false) + 0.2:(state'=29) & (bsearcherfound'= false);
[] state = 19 -> 1.0:(state'=20) & (bsearcherfound'= false);
[] state = 20 -> 0.5:(state'=21) & (bsearcherfound'= false) + 0.3:(state'=23) & (bsearcherfound'= false) + 0.2:(state'=25) & (bsearcherfound'= false);
[] state = 21 -> 1.0:(state'=22) & (bsearcherfound'= false);
[] state = 22 -> 1.0:(state'=60) & (bsearcherfound'= false);
[] state = 23 -> 1.0:(state'=24) & (bsearcherfound'= false);
[] state = 24 -> 1.0:(state'=59) & (bsearcherfound'= false);
[] state = 25 -> 1.0:(state'=26) & (bsearcherfound'= false);
[] state = 26 -> 1.0:(state'=58) & (bsearcherfound'= false);
[] state = 27 -> 1.0:(state'=28) & (bsearcherfound'= true);
[] state = 28 -> 1.0:(state'=57) & (bsearcherfound'= true);
[] state = 29 -> 1.0:(state'=30) & (bsearcherfound'= false);
[] state = 30 -> 0.5:(state'=21) & (bsearcherfound'= false) + 0.3:(state'=23) & (bsearcherfound'= false) + 0.2:(state'=25) & (bsearcherfound'= false);
[] state = 31 -> 1.0:(state'=32) & (bsearcherfound'= false);
[] state = 32 -> 0.5:(state'=19) & (bsearcherfound'= false) + 0.3:(state'=27) & (bsearcherfound'= false) + 0.2:(state'=29) & (bsearcherfound'= false);
[] state = 33 -> 1.0:(state'=34) & (bsearcherfound'= false);
[] state = 34 -> 0.5:(state'=19) & (bsearcherfound'= false) + 0.3:(state'=27) & (bsearcherfound'= false) + 0.2:(state'=29) & (bsearcherfound'= false);
[] state = 35 -> 1.0:(state'=36) & (bsearcherfound'= false);
[] state = 36 -> 0.5:(state'=17) & (bsearcherfound'= false) + 0.2:(state'=33) & (bsearcherfound'= false) + 0.3:(state'=31) & (bsearcherfound'= false);
[] state = 37 -> 1.0:(state'=38) & (bsearcherfound'= false);
[] state = 38 -> 0.5:(state'=17) & (bsearcherfound'= false) + 0.2:(state'=33) & (bsearcherfound'= false) + 0.3:(state'=31) & (bsearcherfound'= false);
[] state = 39 -> 1.0:(state'=40) & (bsearcherfound'= false);
[] state = 40 -> 0.3:(state'=35) & (bsearcherfound'= false) + 0.2:(state'=37) & (bsearcherfound'= false) + 0.5:(state'=15) & (bsearcherfound'= false);
[] state = 41 -> 1.0:(state'=42) & (bsearcherfound'= false);
[] state = 42 -> 0.2:(state'=39) & (bsearcherfound'= false) + 0.5:(state'=10) & (bsearcherfound'= false) + 0.3:(state'=13) & (bsearcherfound'= false);
[] state = 43 -> 1.0:(state'=44) & (bsearcherfound'= false);
[] state = 44 -> 0.2:(state'=39) & (bsearcherfound'= false) + 0.5:(state'=10) & (bsearcherfound'= false) + 0.3:(state'=13) & (bsearcherfound'= false);
[] state = 45 -> 1.0:(state'=46) & (bsearcherfound'= false);
[] state = 46 -> 0.5:(state'=8) & (bsearcherfound'= false) + 0.3:(state'=41) & (bsearcherfound'= false) + 0.2:(state'=43) & (bsearcherfound'= false);
[] state = 47 -> 1.0:(state'=48) & (bsearcherfound'= false);
[] state = 48 -> 0.5:(state'=8) & (bsearcherfound'= false) + 0.3:(state'=41) & (bsearcherfound'= false) + 0.2:(state'=43) & (bsearcherfound'= false);
[] state = 49 -> 1.0:(state'=50) & (bsearcherfound'= false);
[] state = 50 -> 0.5:(state'=6) & (bsearcherfound'= false) + 0.3:(state'=45) & (bsearcherfound'= false) + 0.2:(state'=47) & (bsearcherfound'= false);
[] state = 51 -> 1.0:(state'=52) & (bsearcherfound'= true);
[] state = 52 -> 1.0:(state'=56) & (bsearcherfound'= true);
[] state = 53 -> 1.0:(state'=54) & (bsearcherfound'= false);
[] state = 54 -> 0.3:(state'=49) & (bsearcherfound'= false) + 0.2:(state'=51) & (bsearcherfound'= false) + 0.5:(state'=4) & (bsearcherfound'= false);
[] state = 55 -> 1.0:(state'=56) & (bsearcherfound'= false);
[] state = 56 -> 0.3:(state'=49) & (bsearcherfound'= false) + 0.2:(state'=51) & (bsearcherfound'= false) + 0.5:(state'=4) & (bsearcherfound'= false);
endmodule